server:
  port: 8080
spring:
  datasource:
    password: admin
    username: root
    dbcp2:
      driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/ritweb?useUnicode=true&characterEncoding=utf-8&use
  redis:
    host: localhost
    port: 6379
    password: examplePassword
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl